"""User-facing Excel transaction import template generation."""

from collections.abc import Sequence
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.workbook.defined_name import DefinedName

from account import Account
from category import Category
from excel_workbook import (
    AMOUNT_FORMAT,
    DATE_FORMAT,
    REQUIRED_TRANSACTION_HEADERS,
    save_workbook_atomic,
    style_header_row,
)

INSTRUCTIONS_WORKSHEET = "Instructions"
REFERENCE_DATA_WORKSHEET = "Reference Data"
TEMPLATE_WORKSHEETS = (
    INSTRUCTIONS_WORKSHEET,
    "Transactions",
    REFERENCE_DATA_WORKSHEET,
)
TEMPLATE_ENTRY_LAST_ROW = 1001

INSTRUCTIONS = (
    (
        "Purpose",
        "Enter new Income and Expense transactions for validation, preview, "
        "and all-or-nothing import.",
    ),
    (
        "Workbook",
        "Only .xlsx files are supported. The transaction worksheet must remain "
        "named Transactions.",
    ),
    (
        "Required columns",
        "Date, Type, Amount, Description, Account, and Category are the "
        "required headers. Do not rename them.",
    ),
    (
        "Type",
        "Use Income or Expense.",
    ),
    (
        "Date",
        "Use a real Excel date or supported YYYY-MM-DD text. Future dates are "
        "not allowed.",
    ),
    (
        "Amount",
        "Use a finite numeric amount greater than zero.",
    ),
    (
        "Account",
        "Use the name of an active Account from Reference Data. Do not use a "
        "UUID or display ID.",
    ),
    (
        "Category",
        "Use the name of an active Category from Reference Data. The Category "
        "must match the transaction Type.",
    ),
    (
        "Rows",
        "Completely empty rows are ignored. Partially completed rows are "
        "reported and prevent import.",
    ),
    (
        "Duplicates",
        "Rows matching stored transactions or an earlier workbook row are "
        "conflicts and prevent import.",
    ),
    (
        "Atomic import",
        "Import is all-or-nothing: any validation or duplicate issue imports "
        "zero transactions.",
    ),
    (
        "Identity",
        "Do not supply UUIDs. Internal UUIDs, Display IDs, Created At, and "
        "Updated At values are generated by the application.",
    ),
)


def _fit_print_width(worksheet, print_area: str) -> None:
    worksheet.sheet_properties.pageSetUpPr.fitToPage = True
    worksheet.page_setup.orientation = "landscape"
    worksheet.page_setup.fitToWidth = 1
    worksheet.page_setup.fitToHeight = 1
    worksheet.print_area = print_area
    worksheet.page_margins.left = 0.25
    worksheet.page_margins.right = 0.25
    worksheet.page_margins.top = 0.4
    worksheet.page_margins.bottom = 0.4


def _write_instructions(workbook: Workbook) -> None:
    worksheet = workbook.create_sheet(INSTRUCTIONS_WORKSHEET)
    worksheet.append(("Topic", "Guidance"))
    for topic, guidance in INSTRUCTIONS:
        worksheet.append((topic, guidance))
    style_header_row(worksheet)
    worksheet.freeze_panes = "A2"
    worksheet.column_dimensions["A"].width = 22
    worksheet.column_dimensions["B"].width = 80
    for row in worksheet.iter_rows(min_row=2, max_col=2):
        row[0].font = Font(bold=True, color="1F4E78")
        row[1].alignment = Alignment(vertical="top", wrap_text=True)
    worksheet.sheet_view.showGridLines = False
    _fit_print_width(worksheet, f"A1:B{worksheet.max_row}")


def _add_named_range(
    workbook: Workbook,
    name: str,
    column: str,
    value_count: int,
) -> None:
    last_row = max(value_count + 1, 2)
    workbook.defined_names.add(
        DefinedName(
            name,
            attr_text=(
                f"'{REFERENCE_DATA_WORKSHEET}'!"
                f"${column}$2:${column}${last_row}"
            ),
        )
    )


def _write_reference_data(
    workbook: Workbook,
    accounts: Sequence[Account],
    categories: Sequence[Category],
) -> None:
    worksheet = workbook.create_sheet(REFERENCE_DATA_WORKSHEET)
    active_accounts = [
        account.name for account in accounts if account.is_active
    ]
    income_categories = [
        category.name
        for category in categories
        if category.is_active and category.transaction_type == "income"
    ]
    expense_categories = [
        category.name
        for category in categories
        if category.is_active and category.transaction_type == "expense"
    ]
    all_categories = [*income_categories, *expense_categories]
    headings = (
        ("A1", "Active Accounts"),
        ("C1", "Active Income Categories"),
        ("E1", "Active Expense Categories"),
        ("G1", "All Active Categories"),
    )
    for coordinate, heading in headings:
        worksheet[coordinate] = heading
        cell = worksheet[coordinate]
        cell.fill = PatternFill("solid", fgColor="1F4E78")
        cell.font = Font(color="FFFFFF", bold=True)
        cell.alignment = Alignment(horizontal="center")

    for row, name in enumerate(active_accounts, start=2):
        worksheet.cell(row=row, column=1, value=name)
    for row, name in enumerate(income_categories, start=2):
        worksheet.cell(row=row, column=3, value=name)
    for row, name in enumerate(expense_categories, start=2):
        worksheet.cell(row=row, column=5, value=name)
    for row, name in enumerate(all_categories, start=2):
        worksheet.cell(row=row, column=7, value=name)

    for column in ("A", "C", "E", "G"):
        worksheet.column_dimensions[column].width = 30
    for column in ("B", "D", "F"):
        worksheet.column_dimensions[column].width = 3
    worksheet.freeze_panes = "A2"
    worksheet.sheet_view.showGridLines = False
    _fit_print_width(
        worksheet,
        f"A1:G{max(worksheet.max_row, 2)}",
    )

    _add_named_range(
        workbook,
        "ActiveAccounts",
        "A",
        len(active_accounts),
    )
    _add_named_range(
        workbook,
        "ActiveIncomeCategories",
        "C",
        len(income_categories),
    )
    _add_named_range(
        workbook,
        "ActiveExpenseCategories",
        "E",
        len(expense_categories),
    )
    _add_named_range(
        workbook,
        "ActiveCategories",
        "G",
        len(all_categories),
    )


def _write_transactions(workbook: Workbook) -> None:
    worksheet = workbook.create_sheet("Transactions")
    worksheet.append(REQUIRED_TRANSACTION_HEADERS)
    style_header_row(worksheet)
    worksheet.freeze_panes = "A2"
    worksheet.auto_filter.ref = "A1:F1"
    widths = (16, 14, 16, 44, 28, 28)
    for index, width in enumerate(widths, start=1):
        worksheet.column_dimensions[
            worksheet.cell(row=1, column=index).column_letter
        ].width = width
    worksheet.column_dimensions["A"].number_format = DATE_FORMAT
    worksheet.column_dimensions["C"].number_format = AMOUNT_FORMAT
    _fit_print_width(worksheet, "A1:F2")

    type_validation = DataValidation(
        type="list",
        formula1='"Income,Expense"',
        allow_blank=False,
    )
    account_validation = DataValidation(
        type="list",
        formula1="=ActiveAccounts",
        allow_blank=False,
    )
    category_validation = DataValidation(
        type="list",
        formula1="=ActiveCategories",
        allow_blank=False,
    )
    for validation, cell_range in (
        (type_validation, f"B2:B{TEMPLATE_ENTRY_LAST_ROW}"),
        (account_validation, f"E2:E{TEMPLATE_ENTRY_LAST_ROW}"),
        (category_validation, f"F2:F{TEMPLATE_ENTRY_LAST_ROW}"),
    ):
        validation.error = "Choose a supported value from the list."
        validation.errorTitle = "Invalid template value"
        validation.prompt = "Select a value from the dropdown."
        validation.promptTitle = "Smart Expense Tracker"
        validation.showErrorMessage = True
        validation.showInputMessage = True
        worksheet.add_data_validation(validation)
        validation.add(cell_range)


def build_excel_import_template(
    accounts: Sequence[Account],
    categories: Sequence[Category],
) -> Workbook:
    """Build a template from detached managed-reference data."""
    workbook = Workbook()
    workbook.remove(workbook.active)
    _write_instructions(workbook)
    _write_transactions(workbook)
    _write_reference_data(workbook, accounts, categories)
    return workbook


def generate_excel_import_template(
    accounts: Sequence[Account],
    categories: Sequence[Category],
    destination: Path | str,
    *,
    overwrite: bool = False,
) -> Path:
    """Create and atomically save the user-facing import template."""
    workbook = build_excel_import_template(
        tuple(accounts),
        tuple(categories),
    )
    return save_workbook_atomic(
        workbook,
        destination,
        overwrite=overwrite,
    )
